spring:
  application:
    name: service-consumer
server:
  # 随机端口
  port: 0
eureka:
  client:
    service-url:
      # 注册中心地址 如果由多个地址可以用逗号分割
      defaultZone: http://192.168.56.102:8761/eureka/
    # 单纯的消费者不往注册中心注册服务
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
  instance:
    # 使用ip作为主机名
    prefer-ip-address: true

