spring:
  application:
    name: service-provider
server:
  # 随机端口
  port: 0
eureka:
  client:
    service-url:
      # 注册中心地址 如果由多个地址可以用逗号分割
      defaultZone: http://192.168.56.102:8761/eureka/
  instance:
    # 使用ip作为主机名
    prefer-ip-address: true
    # 使用宿主机ip
    # ip-address: 192.168.56.102

